name: Deploy to EC2

on: push

jobs:
    deploy:
        name: Push to EC2 Instance
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.22
        
            - name: Verify Go installation
              run: go version
            
            - name: Build Go binary
              run: go build -o ./bin ./internal
            
            - name: Deploy to EC2
              uses: easingthemes/ssh-deploy@main
              env:
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                SOURCE: "./"
                REMOTE_HOST: ${{ secrets.EC2_URL }}
                REMOTE_USER: ${{ secrets.EC2_USER }}
                TARGET: ${{ secrets.EC2_DIR }}
